project:
  type: website
  output-dir: docs

website:
  title: "Riesgo Hídrico en Ecuador"
  description: "Análisis y visualización del riesgo hídrico en las provincias del Ecuador utilizando el dataset Aqueduct40."
  navbar:
    right:
      - text: "Inicio"
        href: index.html
      - text: "Análisis"
        href: data_cleaning.html
      - text: "Visualizaciones"
        href: visualizations.html

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 3
    code-fold: true

execute:
  freeze: auto