project:
  type: website
  output-dir: docs

website:
  title: "Riesgo Hídrico en Ecuador"
  description: "Análisis y visualización del riesgo hídrico en las provincias del Ecuador utilizando el dataset Aqueduct 4.0."
  navbar:
    search: true
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Limpieza de Datos"
        href: data_cleaning.qmd
      - text: "Visualizaciones"
        href: visualizations.qmd

format:
  html:
    theme: flatly
    toc: true
    toc-location: right
    toc-depth: 3
    smooth-scroll: true
    code-fold: true
    code-summary: "Mostrar código"
    number-sections: false

execute:
  freeze: auto
